### ISSUE TITLE
Publisher not working on cloud run

### ISSUE THREAD

**Issue by brianschardt** [anchan828/nest-cloud-run-pubsub#215]
So i just deployed the worker, and it is correctly publishing messages to the given topic. 
I have set up permission properly with service accounts(both cloud run services have admin access to pub sub)
The subscription is hitting the cloud run api, however the worker is not processing the messages. 

Any ideas?

**Comment by anchan828** [comment]
Hi,


- Do you see anything in the log on Cloud Run?
- Did you set topic to publisher module? https://github.com/anchan828/nest-cloud-run-pubsub#2-create-publisher-application
- Did you set projectID (if need)

**Comment by anchan828** [comment]
and did you set Worker as provider? 
https://github.com/anchan828/nest-cloud-run-pubsub#add-as-provider

I wanna to get more your information for help :)

**Comment by brianschardt** [comment]
Yep did all that. Ended up getting it working on cloud run :) However, i do have a question about development is it possible to have the worker and publisher outside of docker with env vars like, and the other services in docker.
```
PUBSUB_EMULATOR_HOST=localhost:8681
PUBSUB_PUSH_ENDPOINT=http://localhost:5000
```

**Comment by anchan828** [comment]
yes, you need to install gcloud CLI and pubsub emulator

**Comment by brianschardt** [comment]
got it. and another thing i just found out is, this queue cant be like a prccessing queue, and each job really has a max of 60 seconds to complete

**Comment by brianschardt** [comment]
Also just want to say thanks for all the help. Great packages :)

**Comment by anchan828** [comment]
Let me know if you have any questions :)

**Comment by brianschardt** [comment]
@anchan828 what about processes that take a long time like 5 min. How do those work on cloud run?
